_BASE_: "../../../configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
MODEL:
    ROI_HEADS:
        NUM_CLASSES: 1
    # ANCHOR_GENERATOR:
        # SIZES: [[43], [165], [325], [519], [935]]
        # SIZES: [[45], [153], [302], [505], [925]]
        # SIZES: [[43], [117], [217], [348], [521]]
        # SIZES: [[32], [64], [128], [256], [512]]
        # ASPECT_RATIOS: [[0.3, 0.8, 2.9]]
        # ASPECT_RATIOS: [[0.4, 1.3, 3.1]]
        # ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
SOLVER:
    IMS_PER_BATCH: 4
    # IMS_PER_BATCH: 16
    # BASE_LR: 0.002
    BASE_LR: 0.01
    # BASE_LR: 0.005
    STEPS: (30000, 60000, 90000)
    # STEPS: (35000, 65000, 95000)
    # STEPS: (210000, 250000)
    MAX_ITER: 200000
    WARMUP_ITERS: 50
    # WARMUP_ITERS: 5000
INPUT:
    CROP:
        ENABLED: True
        TYPE: "relative_range"
        SIZE: [0.5, 1.0]
TEST:
    EVAL_PERIOD: 5000
