_BASE_: "../COCO-Detection/faster_rcnn_R_50_FPN_3x_dconv_c3-c5.yaml"
DATASETS:
    TRAIN: ('june2021collated_train',)
    TEST: ('june2021collated_val',)
OUTPUT_DIR: "./output"
DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
MODEL:
    BACKBONE:
        NAME: "build_resnet_fpn_backbone"
    ROI_HEADS:
        NUM_CLASSES: 1
    # ANCHOR_GENERATOR:
    #     SIZES: [[50],[180],[320],[500],[700]]
    #     ASPECT_RATIOS: [[0.5, 1.5, 4.5]]
SOLVER:
    IMS_PER_BATCH: 4
    BASE_LR: 0.01
    STEPS: (40000,70000)
    MAX_ITER: 100000
    WARMUP_ITERS: 5000
    PERIODIC_CHECKPOINTER:
        ENABLED: False
        PERIOD: 10000
    BEST_CHECKPOINTER:
        ENABLED: True
        METRIC: "bbox/AP50"
        MODE: "max"
TEST:
    EVAL_PERIOD: 5000
INPUT:
    # Size of the smallest side of the image during training
    MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
    # Sample size of smallest side by choice or random selection from range give by
    MIN_SIZE_TRAIN_SAMPLING: "choice"
    # Maximum size of the side of the image during training
    MAX_SIZE_TRAIN: 1333
    # Size of the smallest side of the image during testing. Set to zero to disable resize in testing.
    MIN_SIZE_TEST: 800
    # Maximum size of the side of the image during testing
    MAX_SIZE_TEST: 1333
    CROP:
        ENABLED: True
        TYPE: "relative_range"
        SIZE: [0.8,1.0]
    LARGE_SCALE_JITTER:
        ENABLED: True
        MIN_SCALE: 0.5
        MAX_SCALE: 2.0
